create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
create table activities (id integer not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table activity_location (activity_id integer not null, location_id integer not null, primary key (activity_id, location_id)) engine=InnoDB;
create table activity_tag (tag_id integer not null, activity_id integer not null, primary key (tag_id, activity_id)) engine=InnoDB;
create table companies (id integer not null auto_increment, name varchar(255), website_link varchar(255), primary key (id)) engine=InnoDB;
create table location (id integer not null auto_increment, city varchar(255), latitude decimal(38,2) not null, longitude decimal(38,2) not null, phone_number integer not null, street_name varchar(255), street_number integer not null, company_id integer, primary key (id)) engine=InnoDB;
create table tags (id integer not null auto_increment, color varchar(7), name varchar(255), primary key (id)) engine=InnoDB;
create table user_fav_activities (user_id integer not null, activity_id integer not null, primary key (user_id, activity_id)) engine=InnoDB;
create table users (id integer not null auto_increment, admin bit not null, city varchar(255), country varchar(255), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table activity_location add constraint FKtomvvytp2f0vsso8fjaabr3kd foreign key (location_id) references location (id);
alter table activity_location add constraint FKmsyhky43dmn75vw6pri5ypvod foreign key (activity_id) references activities (id);
alter table activity_tag add constraint FKbhdjwvi9htykmwoyjgnq0wabc foreign key (activity_id) references tags (id);
alter table activity_tag add constraint FKif2oaahka2tgme3xh7rbq85on foreign key (tag_id) references activities (id);
alter table location add constraint FKa2n2hljiwhwk0nfy7atk6hhhl foreign key (company_id) references companies (id);
alter table user_fav_activities add constraint FKagl8qkd3xdvwj24pywl4ey326 foreign key (activity_id) references activities (id);
alter table user_fav_activities add constraint FKlucx9ffsajtkcw5dq6vv7opq8 foreign key (user_id) references users (id);
