alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
alter table activity_location drop foreign key FKtomvvytp2f0vsso8fjaabr3kd;
alter table activity_location drop foreign key FKmsyhky43dmn75vw6pri5ypvod;
alter table activity_tag drop foreign key FKbhdjwvi9htykmwoyjgnq0wabc;
alter table activity_tag drop foreign key FKif2oaahka2tgme3xh7rbq85on;
alter table location drop foreign key FKa2n2hljiwhwk0nfy7atk6hhhl;
alter table user_fav_activities drop foreign key FKagl8qkd3xdvwj24pywl4ey326;
alter table user_fav_activities drop foreign key FKlucx9ffsajtkcw5dq6vv7opq8;
drop table if exists activities;
drop table if exists activity_location;
drop table if exists activity_tag;
drop table if exists companies;
drop table if exists location;
drop table if exists tags;
drop table if exists user_fav_activities;
drop table if exists users;
